# Generated by Django 3.2.19 on 2023-06-05 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
